setup so far
Vault-Hill/vhc-marketplace-app pull request #1
Opened 2022-02-09 14:38 UTC by creativogee

Done
- TailwindCSS bootstrapping
- Created reusable asset card component
- Initialized state management with redux toolkit

2022-02-10 03:10 UTC, anjorinjnr commented
I added some styling enforcement and CI stuff.

On the structure, here is what I suggest
```
/src
  /assets 
  /services
  /state // redux stuff here
  /utils
  /hooks
  /features
     /shared   
        /layout 
           ... shared layout components
     ... feature components e.g Alert, Button, Form, Modal etc
  index.tsx
  App.tsx
  route.ts
  ... other files.
```
Remove abstractions (the interfaces can live right inside the component defining it)
Remove components (everything is pretty much a component)
I am not sure what will go inside hoc, lib,  and statics. I will remove unless you know what will go there.

2022-02-10 03:10 UTC, anjorinjnr requested changes
See comment

2022-02-14 13:31 UTC, jmulq commented on .eslintrc.js
> +    'react/require-default-props': 0,
Is this needed with typescript?

2022-02-14 13:31 UTC, jmulq commented on .eslintrc.js
> +    'react/prop-types': 0,
Same as above, is this needed? We won't be using prop types.

2022-02-14 13:31 UTC, jmulq commented on .eslintrc.js
> +    'react/no-unused-prop-types': 0,
Is this needed?

2022-02-14 13:31 UTC, jmulq commented on package.json
>      "@testing-library/jest-dom": "^5.16.2",
Should testing dependencies go into dev dependenices? Feels like they should buy I'm not too sure. @anjorinjnr ?

2022-02-14 13:31 UTC, jmulq commented on package.json
> +    "build": "react-scripts build",
Need a prod start script eventually I believe? Otherwise will encounter the same issue we had with website deployment, any thoughts on this @anjorinjnr

2022-02-14 13:31 UTC, jmulq commented on src/features/shared/AssetCard.tsx
> +interface IAssetCard {
Should this just be `Props`?

2022-02-14 15:01 UTC, creativogee commented on src/features/shared/AssetCard.tsx
> +interface IAssetCard {
essentially it could just be Props since it is only used in the component.

2022-02-21 13:55 UTC, anjorinjnr commented on .eslintrc.js
> +    'react/no-unused-prop-types': 0,
it checks with typescript too

2022-02-21 14:10 UTC, merged