feat: create bid
Vault-Hill/vhc-marketplace-app pull request #108
Opened 2022-04-26 08:05 UTC by creativogee

## Description

marketplace user can place bid on asset

2022-04-26 09:01 UTC, jmulq requested changes

2022-04-26 11:41 UTC, creativogee commented on src/features/shared/TextInput.tsx
> +  useEffect(() => {
Not it wont. It only evaluates when there is an meta.error is truthy

2022-04-26 12:02 UTC, creativogee commented on src/features/partials/Popups/Payment.tsx
> +      setIsConfirming(false)
I removed earlier. Can add that back that in the meantime but the idea is to handle all possible errors

2022-04-26 12:16 UTC, creativogee commented on src/features/partials/Popups/Payment.tsx
> +  useEffect(() => {
Yes it is does happen when user clicks approve button except this approve is more efficient because, the click event is asynchronous, causes a side effect that trigger the hook when makerSwapAsset state variable is set.

2022-04-26 12:40 UTC, creativogee commented on src/features/partials/Popups/Payment.tsx
> +      const provider = new ethers.providers.Web3Provider(
Agreed, makes sense as a global state.

2022-04-26 13:37 UTC, jmulq commented on src/features/partials/Popups/Payment.tsx
> +  useEffect(() => {
Awesome. Thanks for the clarification.

2022-04-27 10:07 UTC, jmulq approved these changes

2022-04-27 10:13 UTC, jmulq approved these changes

2022-04-27 10:15 UTC, merged