feat: cancel buy now from listing
Vault-Hill/vhc-marketplace-app pull request #110
Opened 2022-04-26 09:30 UTC by chandni-vault-hill

## Description

2022-04-27 12:17 UTC, jmulq requested changes

2022-04-27 12:19 UTC, chandni-vault-hill commented on src/services/queries.ts
> +export const ASSET_DATA_FETCHER = asset$.tokenId.tokenAddress
Yes to cancel the buy now, need two inputs, will need this

2022-04-27 12:25 UTC, chandni-vault-hill commented on src/features/partials/Popups/CancelBuyNow.tsx
> +    const { tokenId, tokenAddress } = buyNow as Asset
Yes it was complaining for undefined, but will keep a check

2022-04-27 12:43 UTC, chandni-vault-hill commented on src/features/partials/Popups/SellAssetSubmitted.tsx
> +  const params: any = useParams() as { tokenId: string }
Fixed

2022-04-28 10:26 UTC, jmulq requested changes

2022-04-28 10:26 UTC, jmulq commented on src/features/partials/AssetDetails/index.tsx
> +  const handleSaleClick = () => {
Just split this into two functions. Sale isn't being clicked when we unlist. I would just have `handleSell` and `handleUnlist` or something similar

2022-04-28 10:26 UTC, jmulq commented on src/features/partials/Popups/SellAssetSubmitted.tsx
> +  const params: { tokenId: string } = useParams() as { tokenId: string }
you don't need to cast this. `useParams<{ tokenId: string }>()` should work.

2022-04-28 10:52 UTC, chandni-vault-hill commented on src/features/partials/Popups/SellAssetSubmitted.tsx
> +  const params: { tokenId: string } = useParams() as { tokenId: string }
Fixed

2022-04-28 10:53 UTC, chandni-vault-hill commented on src/features/partials/AssetDetails/index.tsx
> +  const handleSaleClick = () => {
Separated the functions

2022-04-28 13:10 UTC, jmulq approved these changes

2022-04-28 13:11 UTC, merged