fix: taker address in create sell now
Vault-Hill/vhc-marketplace-app pull request #121
Opened 2022-04-27 09:54 UTC by chandni-vault-hill

## Description

https://github.com/Vault-Hill/vhc-marketplace-app/issues/119

2022-04-27 12:19 UTC, jmulq requested changes

2022-04-27 12:19 UTC, jmulq commented on src/features/partials/Popups/ConfirmSell.tsx
> +          tokenAddress: process.env.REACT_APP_VHC_ADDRESS!,
This is not correct. It should be getting the data from wherever the user sets the specific currency they want. This would work for now whilst we're only supporting VHC, but break as soon as we introduce new currencies. Can you not get this from the buy now?

2022-04-27 13:38 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +          tokenAddress: process.env.REACT_APP_VHC_ADDRESS!,
Yes got it from getERC20TokenAddress(buyNow.currency)

2022-04-28 10:30 UTC, jmulq approved these changes

2022-04-28 10:40 UTC, merged