fix: expiry date buy now listing
Vault-Hill/vhc-marketplace-app pull request #183
Opened 2022-05-12 13:06 UTC by chandni-vault-hill

## Description

https://github.com/Vault-Hill/vhc-marketplace-app/issues/158

2022-05-12 13:16 UTC, creativogee requested changes

2022-05-12 13:16 UTC, creativogee commented on src/features/partials/AssetDetails/index.tsx
> +                          Bid active till
I think the message may be incorrect. Why not "Sale ends on" then "Sale ended on" when time elapse before it is then unmounted when transaction is complete

2022-05-12 13:19 UTC, chandni-vault-hill commented on src/features/partials/AssetDetails/index.tsx
> +                          Bid active till
Yes, sure thing.

2022-05-12 14:29 UTC, creativogee requested changes

2022-05-12 14:29 UTC, creativogee commented on src/features/partials/AssetDetails/index.tsx
> +                          {new Date(endDate ?? 0).getTime() - Date.now() <= 0
there is a utility function for this. isDateElapsed()

2022-05-13 08:16 UTC, chandni-vault-hill commented on src/features/partials/AssetDetails/index.tsx
> +                          {new Date(endDate ?? 0).getTime() - Date.now() <= 0
Okay

2022-05-13 12:46 UTC, creativogee approved these changes

2022-05-13 12:46 UTC, merged