build: landing page, closes issue #12
Vault-Hill/vhc-marketplace-app pull request #56
Opened 2022-02-25 21:26 UTC by creativogee

## Description
Closes #12 

Build a fully responsive and adaptive landing page wherein marketplace users can view available assets
### This commit consists of the following:
- Reusable Header component
- Reusable Hero section
- Fully reusable asset listing component
- Reusable promotion section
- Reusable Foter component

### This commit does not include:
- Asset Filter component
- Functionality

2022-02-26 14:57 UTC, anjorinjnr requested changes
there were merge conflicts that weren't resolved. I've resolved them but be careful when you do rebase to make sure any conflict is resolved. It's possible you also left the conflicts intentionally for me to resolve in this case and that's fine.


I noticed some inconsistencies in the folder structure
- looks like you have a folder for each main component and then the sub components in `partials` folder or `modules` folders. This patten is okay but we should stick to one. 

Personally I find modules confusing just because modules have a specific meaning in javascript.

My preference is this, if a component can stand alone just create a single file
`Foo.tsx` and export the default.

if the component needs to be broken down
create a folder `foo`, with `Foo.tsx`  export default, and then create `FooBar.tsx`, `FooBuz.tsx` in the folder and export the components. If think the `partials` subfolder is just another unnecessary nesting as one can always tell the main component from the others. 

Either ways as long it's consistent that's fine.

I made a few structural changes

2022-02-26 19:03 UTC, creativogee commented
> there were merge conflicts that weren't resolved. I've resolved them but be careful when you do rebase to make sure any conflict is resolved. It's possible you also left the conflicts intentionally for me to resolve in this case and that's fine.
> 
> I noticed some inconsistencies in the folder structure
> 
> * looks like you have a folder for each main component and then the sub components in `partials` folder or `modules` folders. This patten is okay but we should stick to one.
> 
> Personally I find modules confusing just because modules have a specific meaning in javascript.
> 
> My preference is this, if a component can stand alone just create a single file `Foo.tsx` and export the default.
> 
> if the component needs to be broken down create a folder `foo`, with `Foo.tsx` export default, and then create `FooBar.tsx`, `FooBuz.tsx` in the folder and export the components. If think the `partials` subfolder is just another unnecessary nesting as one can always tell the main component from the others.
> 
> Either ways as long it's consistent that's fine.
> 
> I made a few structural changes

I actually resolved the conflicts during rebasing for the build/landing branch only for them to reappear on PR so closed the PR and tried to merge build/landing with develop locally, resolved the conflict again then when I pushed it said "Already up to date" so I left it for you.

Will implement the suggested changes immediately.

2022-03-01 13:30 UTC, anjorinjnr approved these changes

2022-03-01 13:39 UTC, anjorinjnr approved these changes

2022-03-01 13:39 UTC, merged