Feat/landing typology filter, closes issue #57
Vault-Hill/vhc-marketplace-app pull request #58
Opened 2022-03-01 16:23 UTC by creativogee

## Description

This commit contains:
- Responsive component with which a marketplace user could filter asset list: Filter options include virtual land typologies

This commit does not contain:
- Functionality

2022-03-02 03:18 UTC, anjorinjnr commented
I am confused about this UI?

Is this the typology filter?

<img width="792" alt="image" src="https://user-images.githubusercontent.com/1556093/156288329-b2769259-0dfd-4fdf-82f4-4e84c2ed71f7.png">

What is a user supposed to type in the search box?

Also the drop down listsour land types? That's very restrictive. That dropdown should probably be asset types (LAND, ART, etc)

2022-03-02 03:19 UTC, anjorinjnr requested changes
see my comment

2022-03-02 03:20 UTC, anjorinjnr commented
And shouldn't close until they are functional unless we plan to or have another issue for implementing the functionality

2022-03-02 07:00 UTC, creativogee commented
This part is
![image](https://user-images.githubusercontent.com/65257219/156310683-315c3559-c826-48b0-9272-63a5e1ecd7d9.png)
What you highlighted is the search component. I believe the idea behind that is to have a finer-grained search like searching by name. Also, my guess is those options are like that in the dropdown because VLAND is the only asset for now.

2022-03-02 07:05 UTC, creativogee commented
> And shouldn't close until they are functional unless we plan to or have another issue for implementing the functionality

Actually most tickets, for now, say to just build it out. We could create new tickets to implement the functionality, we could as well wait until functionality is implemented

2022-03-02 11:13 UTC, jmulq commented
> > And shouldn't close until they are functional unless we plan to or have another issue for implementing the functionality
> 
> Actually most tickets, for now, say to just build it out. We could create new tickets to implement the functionality, we could as well wait until functionality is implemented

The build out tickets are for building out the functionality/logic as well as the UI. If we're creating new components that don't implement any of the logic, lets call them scaffold. Also could they be tagged appropriately.

2022-03-02 11:17 UTC, jmulq commented on src/features/elements/TypologyFilter.tsx
> +            className={`whitespace-nowrap pb-2 mb-2 md:mb-0 md:pb-4 px-1 border-b-2 font-medium text-sm cursor-pointer
Have you heard of the `classnames` package? Is a cleaner way of doing this. Might be worth implementing it across the project https://www.npmjs.com/package/classnames.

2022-03-02 11:17 UTC, jmulq commented on src/pages/home/index.tsx
> +      <TypologyFilter />
How are we planning to change the assets passed down to the `AssetListing` component from the `TypologyFilter`?  Just wondering

2022-03-02 12:41 UTC, creativogee commented on src/pages/home/index.tsx
> +      <TypologyFilter />
> How are we planning to change the assets passed down to the `AssetListing` component from the `TypologyFilter`? Just wondering

We could use the store to achieve that

2022-03-02 12:57 UTC, creativogee commented on src/features/elements/TypologyFilter.tsx
> +            className={`whitespace-nowrap pb-2 mb-2 md:mb-0 md:pb-4 px-1 border-b-2 font-medium text-sm cursor-pointer
> Have you heard of the `classnames` package? Is a cleaner way of doing this. Might be worth implementing it across the project https://www.npmjs.com/package/classnames.

Alright noted

2022-03-02 13:28 UTC, creativogee commented
> > > And shouldn't close until they are functional unless we plan to or have another issue for implementing the functionality
> > 
> > 
> > Actually most tickets, for now, say to just build it out. We could create new tickets to implement the functionality, we could as well wait until functionality is implemented
> 
> The build out tickets are for building out the functionality/logic as well as the UI. If we're creating new components that don't implement any of the logic, lets call them scaffold. Also could they be tagged appropriately.

That makes sense, at the time there was no server to make requests to and the store was not set up. Also, this current ticket did not have a dependency on a server ticket. So, should I create a new ticket that says scaffold while I probably focus on setting up the redux store on a separate?

2022-03-02 14:33 UTC, anjorinjnr commented on src/features/elements/TypologyFilter.tsx
> +            className={`whitespace-nowrap pb-2 mb-2 md:mb-0 md:pb-4 px-1 border-b-2 font-medium text-sm cursor-pointer
this package is 20kb, do we need it?

A util function like this is sufficient
```
export const classNames = (...classes: string[]) =>
  classes.filter(Boolean).join(' ')
```
you can do something like 
```
<CheckIcon
    className={classNames(
       pctCompleted === 100 ? 'text-green-600' : 'text-gray-500',
       'h-5 w-5'
       )}
 />
```

2022-03-02 14:36 UTC, anjorinjnr commented
> This part is ![image](https://user-images.githubusercontent.com/65257219/156310683-315c3559-c826-48b0-9272-63a5e1ecd7d9.png) What you highlighted is the search component. I believe the idea behind that is to have a finer-grained search like searching by name. Also, my guess is those options are like that in the dropdown because VLAND is the only asset for now.

This doesn't generalize. Unless we are building a vland specific page.

We should keep in that vland are not the only thing that will be traded in the markerplace.

I thought we can building the side filter, which we can generate from the asset metadata and will be dynamic.

2022-03-02 14:37 UTC, anjorinjnr commented
> > > And shouldn't close until they are functional unless we plan to or have another issue for implementing the functionality
> > 
> > 
> > Actually most tickets, for now, say to just build it out. We could create new tickets to implement the functionality, we could as well wait until functionality is implemented
> 
> The build out tickets are for building out the functionality/logic as well as the UI. If we're creating new components that don't implement any of the logic, lets call them scaffold. Also could they be tagged appropriately.

Either option is fine for me, make be for planning purposed might be easier to use different issues. Just name and tag them propertly.

@jmulq  @abbeydabiri  fyi

2022-03-02 14:38 UTC, anjorinjnr commented
> I am confused about this UI?
> 
> Is this the typology filter?
> 
> <img alt="image" width="792" src="https://user-images.githubusercontent.com/1556093/156288329-b2769259-0dfd-4fdf-82f4-4e84c2ed71f7.png">
> 
> What is a user supposed to type in the search box?
> 
> Also the drop down lists our land types? That's very restrictive. That dropdown should probably be asset types (LAND, ART, etc)

we should remove search for now.

2022-03-03 22:45 UTC, creativogee commented on src/features/elements/TypologyFilter.tsx
> +            className={`whitespace-nowrap pb-2 mb-2 md:mb-0 md:pb-4 px-1 border-b-2 font-medium text-sm cursor-pointer
> this package is 20kb, do we need it?
> 
> A util function like this is sufficient
> 
> ```
> export const classNames = (...classes: string[]) =>
>   classes.filter(Boolean).join(' ')
> ```
> 
> you can do something like
> 
> ```
> <CheckIcon
>     className={classNames(
>        pctCompleted === 100 ? 'text-green-600' : 'text-gray-500',
>        'h-5 w-5'
>        )}
>  />
> ```

agreed, less bundle size

2022-03-06 17:47 UTC, closed without merging