feat: asset details UI
Vault-Hill/vhc-marketplace-app pull request #68
Opened 2022-03-18 14:20 UTC by chandni-vault-hill

## Description

 
Task Link: https://github.com/Vault-Hill/vhc-marketplace-app/issues/22

2022-03-21 12:25 UTC, creativogee requested changes

2022-03-21 12:25 UTC, creativogee commented on src/features/partials/AssetsListing/AssetsListing.tsx
> +                    onClick={() => {
There is a gotcha with this implementation. The asset that is being sent as the state most likely will not contain everything the asset details page needs to render which is what this current implementation is assuming.

My suggestion is to wrap the AssetCard in anchor tag with its href attribute taking us to asset details page why the data it needs to render are fetched on demand use RTK custom hooks.

2022-03-21 12:25 UTC, creativogee commented on src/features/elements/AssetCard.tsx
> +  onClick
see comment below. The onClick will not be needed. @jmulq @chandni-vault-hill @anjorinjnr

2022-03-21 12:35 UTC, chandni-vault-hill commented on src/features/elements/AssetCard.tsx
> +  onClick
I require it to navigate it to asset details page, it could be made optional

2022-03-21 12:37 UTC, chandni-vault-hill commented on src/features/partials/AssetsListing/AssetsListing.tsx
> +                    onClick={() => {
Yes, but as for now the other values are not their being sent from api such as bids and sales history, For initial stage I just mapped them with the data I had already, however will make these changes

2022-03-21 14:51 UTC, jmulq commented on src/assets/images/icons/currency.svg
> +<svg width="28" height="29" viewBox="0 0 28 29" fill="none" xmlns="http://www.w3.org/2000/svg">
How comes the formatting on this file is off? Can we run a formatter and get this to proper formatting?

2022-03-21 14:51 UTC, jmulq commented on src/assets/images/icons/heart.svg
> +<svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg">
Same as above

2022-03-21 14:53 UTC, jmulq commented on src/features/elements/Properties.tsx
> +const Properties = ({ properties }: Props) => {
Calling this `AssetProperties` might make more sense? Thoughts? @creativogee

2022-03-21 14:54 UTC, jmulq commented on src/features/partials/AssetDetails/AssetDetails.tsx
> +import { Tab } from '@headlessui/react'
Out of curiosity, why are we using this instead of tailwind?

2022-03-23 07:59 UTC, chandni-vault-hill commented on src/assets/images/icons/currency.svg
> +<svg width="28" height="29" viewBox="0 0 28 29" fill="none" xmlns="http://www.w3.org/2000/svg">
Formatted this part

2022-03-23 08:00 UTC, chandni-vault-hill commented on src/assets/images/icons/heart.svg
> +<svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg">
Done

2022-03-23 10:25 UTC, creativogee requested changes
- rebase
- use button component
- remove short circuit and data property in src\pages\details\index.tsx
- rename src\pages\details -> src\pages\asset-details
- put recommended into src\pages\asset-details\index.tsx
- call the useGetAssetByTokenIdQuery hook inside src\features\partials\AssetDetails\AssetDetails.tsx wrap with useEffect

2022-03-23 20:33 UTC, creativogee approved these changes

2022-03-23 20:34 UTC, merged