feat: auction modals
Vault-Hill/vhc-marketplace-app pull request #75
Opened 2022-03-28 16:18 UTC by creativogee

## Description
Create the remaining 3 modals for the auction flow.
This is tested by changing the first switch statement to the modal of interest

2022-03-29 13:30 UTC, jmulq approved these changes
Looks good. Might be worth added a modals folder to partials? Presume there can be more than just modals in the partials folder?

2022-03-29 13:30 UTC, jmulq commented on src/features/partials/Popups/BidSubmitted.tsx
> +        <h1 className='text-2xl my-4'>You bid has been submitted</h1>
Typo, should be your

2022-03-29 13:30 UTC, jmulq commented on src/features/partials/Popups/index.tsx
> +  switch (popups.modal.at(-1)) {
Why are we checking against the modal at `-1`? What does this do?

2022-03-29 13:52 UTC, creativogee commented on src/features/partials/Popups/index.tsx
> +  switch (popups.modal.at(-1)) {
Initially, it was not an array, now we have implemented a stack for the modals cos the design has a back button for certain modals. So the modal on the top of the stack is the modal that is shown.

2022-03-29 13:57 UTC, creativogee commented
> Looks good. Might be worth added a modals folder to partials? Presume there can be more than just modals in the partials folder?

Yes, there is a folder created that is supposed to contain all modals and notification/alert components. It is called Popups. Do you reckon we should have that renamed to modals and have a separate folder for notification/alert components?

2022-03-30 10:16 UTC, jmulq commented
> > Looks good. Might be worth added a modals folder to partials? Presume there can be more than just modals in the partials folder?
> 
> Yes, there is a folder created that is supposed to contain all modals and notification/alert components. It is called Popups. Do you reckon we should have that renamed to modals and have a separate folder for notification/alert components?

Ye something like that. Or the popups folder could contain a folder for each type. whatever you think works :)

2022-03-30 10:25 UTC, jmulq commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +              {category.replace(/([A-Z]+)*([A-Z][a-z])/g, '$1 $2')}
What is this doing? I tend to prefer logic like this to sit outside of the return statement. For example you could have a method that you pass the category to, which returns this string. Name it appropriately and then its obvious what it does at a glance. It also splits the logic up so its not just one massive JSX return statement.

No need to change anything here but definitely worth considering and maybe playing/testing with in the future

2022-03-30 10:25 UTC, jmulq commented on src/index.css
> +/* body {
Delete?

2022-03-30 10:25 UTC, jmulq commented on src/pages/landing/Hero.tsx
> +          Vault Hill Ciy Marketplace
Typo - City

2022-03-30 10:25 UTC, jmulq commented on src/types.ts
> +  ALPHA,
Why is this now not an enum?

2022-04-01 14:18 UTC, creativogee commented on src/types.ts
> +  ALPHA,
It's an enum innit?

2022-04-01 14:25 UTC, jmulq commented on src/types.ts
> +  ALPHA,
Thinking about it. I don't even know if we'll need this as we can just get it from the generated schema.

2022-04-01 14:26 UTC, jmulq commented on src/types.ts
> +  ALPHA,
Yep, look in the enums folder in the generated schema.

2022-04-01 14:27 UTC, jmulq commented
Conflicting files need resolving.

2022-04-01 14:43 UTC, anjorinjnr requested changes

2022-04-01 14:43 UTC, anjorinjnr commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +const SalesHistory = ({ panels }: { panels: any }) => {
why is panels `any`? can't we define a type for it?

2022-04-01 14:43 UTC, anjorinjnr commented on src/features/partials/AssetsListing/index.tsx
>          {/* <div className='mt-8 text-sm md:hidden'>
delete

2022-04-01 14:43 UTC, anjorinjnr commented on src/features/partials/Popups/Payment.tsx
> +    if (popups.modal.at(-2) === Popup.PLACE_BID) {
this is not readable

2022-04-01 14:43 UTC, anjorinjnr commented on src/fake-data/assets.ts
>  export const assets = [
i thought we have data from the server, why do we still need this?

2022-04-01 14:43 UTC, anjorinjnr commented on src/__generated/fetchers/AssetFetcher.ts
> +asset$.tokenId.tokenAddress.tokenUri.createdAtTimestamp.creator.owner
better to format this one field per line to make it readable

2022-04-01 14:43 UTC, anjorinjnr commented on src/__generated/fetchers/ListingFetcher.ts
> +export const listing$$ = listing$.assetId.assetAddress.type.status.order
same as above

2022-04-01 14:43 UTC, anjorinjnr commented on src/features/partials/Popups/PlaceBid.tsx
> +const balance = {
what is this for?

2022-04-01 14:43 UTC, anjorinjnr commented on src/features/partials/Popups/PlaceBid.tsx
> +                      {/* eslint-disable-next-line @typescript-eslint/no-shadow */}
??

2022-04-01 14:43 UTC, anjorinjnr commented on src/features/shared/header/Header.tsx
> +// import { useState } from 'react'
why is all these commented out?

2022-04-01 14:43 UTC, anjorinjnr commented on src/state/popup.slice.ts
> +      state.modal = []
if the modal is a stack, why doesn't close only remove the last modal instead it  removes all modals.  I think the API is gonna be confusing to use.

if prevModal is called when the stack is empty what happens, nothing I guess?

2022-04-01 14:43 UTC, anjorinjnr commented on src/state/popup.slice.ts
> +      state.modal = []
where there's a sequence of modals, should the component in charge handle that instead of the modal state?

2022-04-01 14:43 UTC, anjorinjnr commented on src/types.ts
> +  ALPHA,
yes use the generated types, you can alias the types where it's convenient

2022-04-01 15:10 UTC, creativogee commented on src/index.css
> +/* body {
We actually using all 3

2022-04-01 15:26 UTC, creativogee commented on src/types.ts
> +  ALPHA,
We need some of the enums for string comparison. Others I can take out

2022-04-01 15:35 UTC, creativogee commented on src/features/partials/AssetsListing/index.tsx
> +        {loading || fetching ? (
Sure. So many cleanups we will need to do later on

2022-04-01 15:37 UTC, creativogee commented on src/features/shared/header/Header.tsx
> +                    {connected ? (
Abbey has not shared the implementation for the wallet connect with mobile view. So they were erroring out and blocking. Commented those out to unblock

2022-04-01 15:40 UTC, creativogee commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +const SalesHistory = ({ panels }: { panels: any }) => {
We could. Just a quick walkaround. Will change that one now.  There are some more "any" types we will need to remove subsequenly

2022-04-01 15:46 UTC, creativogee commented on src/fake-data/assets.ts
>  export const assets = [
The file is no longer need

2022-04-01 16:11 UTC, creativogee commented on src/features/partials/Popups/Payment.tsx
> +    if (popups.modal.at(-2) === Popup.PLACE_BID) {
I have added this comment to the code: 
There is only one payment modal for BUY_NOW flow and AUCTION flow, so this function help to determine which one, it then shows the appropriate confirmation modal which is either ORDER_CONFIRMED or BID_SUBMITTED. ORDER_CONFIRMED is the default nextModal

2022-04-01 16:12 UTC, creativogee commented on src/fake-data/assets.ts
>  export const assets = [
Actually some files are still needed in there

2022-04-01 16:18 UTC, creativogee commented on src/features/partials/Popups/PlaceBid.tsx
> +const balance = {
There is a currency dropdown on that modal.
![image](https://user-images.githubusercontent.com/65257219/161302816-e3752b12-7608-4b7f-97c4-667e6da044bb.png)

2022-04-01 16:21 UTC, creativogee commented on src/features/shared/header/Header.tsx
> +// import { useState } from 'react'
It was erroring out. @abbeydabiri's implementation only covered the desktop view as the desktop view connect wallet impl was isolated out into it's own file @anjorinjnr

2022-04-01 16:50 UTC, creativogee commented on src/state/popup.slice.ts
> +      state.modal = []
> if the modal is a stack, why doesn't close only remove the last modal instead it removes all modals. I think the API is gonna be confusing to use.
> 
> if prevModal is called when the stack is empty what happens, nothing I guess?

My thought was if we have stacked modals for buy now flow, and then we switch to an auction flow, if we start to back up from auction flow we're going to find ourselves in the buy now flow. Also if we don't clear the stack it's going to keep growing.

About the prevModal
The ideal situation (there is never an ideal situation but) is that the stack can only be empty when there is no opened modal in which case prevModal cannot be called.

2022-04-05 08:54 UTC, jmulq commented on src/types.ts
> +  ALPHA,
The generated enum types should cover this though right?

2022-04-05 08:54 UTC, jmulq commented on src/features/shared/header/Header.tsx
> +                    {connected ? (
Is Abbey aware of the mobile wallet connection issue?

2022-04-05 09:26 UTC, jmulq requested changes

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +              className={classNames(
I though `classNames` takes an array of strings? Do we even need to use this function here if its just that one string we're passing in. There's also a `classnames` package that might make more sense using.

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +                            {value.replace(/([A-Z]+)*([A-Z][a-z])/g, '$1 $2')}
Whats happening here? If code is hard to understand at a glance, it makes more sense to move in into a function where the name describes what it is doing. Otherwise I find react projects just get to a point where its a load of JSX which is incredibly hard to decipher.

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +                    {panels[keyName].map((obj: any, index: number) => (
Similar to comment above. What are we rendering here? Could it be extracted out into a function before the return called something like `renderPanelBody`? We want the project to be as easy to read, and maintainable as possible.

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +                    {panels[keyName].map((obj: any, index: number) => (
Not needed to be changed before merging, but something to think about going forward.

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetDetails/index.tsx
> +  const [asset, setAsset] = useState<any>()
This needs a proper type, however leave it as I will sort when merging this into my branch.

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetDetails/index.tsx
> +    let modal = ''
Maybe just not declare a var here, and dispatch the correct popup in the if statements? That's all we want to do right. No need to assign it

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetDetails/index.tsx
> +    let modal = ''
So it'd be 

```
if (asset?.listing....) {
  dispatch(openModal(Popup.PLACE_BID))
}
```

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetsListing/index.tsx
> +  loading: boolean
Do we need `fetching` and `loading`? They both are just being used for the exact same logic. I'd remove `fetching`.

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/AssetsListing/index.tsx
> +  data,
What's the reasoning for now passing in `data` now instead of `assets`? And then setting some state called `assets` to `data`?

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/Popups/Payment.tsx
> +    if (popups.modal.at(-2) === Popup.PLACE_BID) {
I think this can be done simpler. Can you not just pass some prop to the component that is used to determine what flow we are on. `paymentType` or something? Which could use the listing type enum or something (auction or buy now)?

Thoughts on this? @creativogee  @anjorinjnr

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/Popups/PlaceBid.tsx
> +const balance = {
We're going to need to add a task to make some changes to this. Auctions should probably have an `prices` field associated with them, which is an array of `Price`.

Would look something like:
`Price: [ { currency: 'VHC', value: 1000 }, { currency: 'ETH', value: 0.1 } ]`

For now, add a todo on the relevant code so we can come back and resolve. This iteration will only need VHC as an accepted means of payment.

2022-04-05 09:26 UTC, jmulq commented on src/features/partials/Popups/PlaceBid.tsx
> +      {/* Button section */}
Delete

2022-04-05 09:26 UTC, jmulq commented on src/features/shared/header/Header.tsx
> +// import { useState } from 'react'
Can we raise this in huddle. This will need to be resolved for mobile.

2022-04-05 09:26 UTC, jmulq commented on src/pages/landing/index.tsx
> +        skeleton={8}
What is skeleton? Couldn't work out here on in the `AssetsListing` component. Why is it a number?

2022-04-05 09:26 UTC, jmulq commented on src/state/popup.slice.ts
> +      state.modal = []
Maybe the component in charge has some `const`'s which dictate the order of each flow? An array for each flow which has the modals in there sequence? That way we wouldn't need the logic which figures out based on the popup at the beginning of the stack?

2022-04-05 09:26 UTC, jmulq commented on src/utils/index.ts
> +export const truncate = (address: string, n: number, m?: number) => {
The params `n` and `m?` could be named better. Make it as obvious as possible what they are to the function.

2022-04-05 11:36 UTC, creativogee commented on src/types.ts
> +  ALPHA,
Already using some of the generated types for typecasting. However, the Vland and Asset are not in the generated types, Listing,  ListingDetails, FillDetails, Auction, and more. Also, we cant use types for string comparison, we need a string enum for that or an object literal. I don't it should not be a blocker, once all required types are available in the generated types we will switch things up

2022-04-05 11:38 UTC, creativogee commented on src/features/shared/header/Header.tsx
> +                    {connected ? (
I believe so. He has been tagged in the comments. He could fix that in a separate PR

2022-04-05 11:43 UTC, creativogee commented on src/features/partials/Popups/PlaceBid.tsx
> +const balance = {
Agreed. We can create an issue to have that implemented on both ends

2022-04-05 12:03 UTC, creativogee commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +              className={classNames(
True. There will be some more clean-ups to be done in those components tbh. I already did a lot of refactoring and restructuring from the old code. I guess we can clean things up as we go

2022-04-05 12:05 UTC, creativogee commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +                            {value.replace(/([A-Z]+)*([A-Z][a-z])/g, '$1 $2')}
These are from the old code. I could fix all of that now but it will delay this PR longer than it already is

2022-04-05 12:06 UTC, creativogee commented on src/features/partials/AssetDetails/index.tsx
> +  const [asset, setAsset] = useState<any>()
Agreed. Once we generate the types

2022-04-05 12:13 UTC, creativogee commented on src/features/partials/Popups/PlaceBid.tsx
> +      {/* Button section */}
Delete the comment?

2022-04-05 12:15 UTC, creativogee commented on src/pages/landing/index.tsx
> +        skeleton={8}
The prop simply tells the component how many skeletons it needs to render while fetching.

2022-04-05 12:39 UTC, jmulq commented on src/types.ts
> +  ALPHA,
Okay sounds good. Will resolve this for now and we can fix up the types once I've merged my branch in (as it has some of the types we need).

2022-04-05 12:40 UTC, jmulq commented on src/features/partials/Popups/PlaceBid.tsx
> +const balance = {
I'll create an issue for this now in the backlog.

2022-04-05 12:42 UTC, jmulq commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +              className={classNames(
Yep sounds good. I'll resolve this.

2022-04-05 12:42 UTC, jmulq commented on src/features/partials/AssetDetails/SalesHistory.tsx
> +                            {value.replace(/([A-Z]+)*([A-Z][a-z])/g, '$1 $2')}
Yep don't resolve for this PR. Will resolve this.

2022-04-05 12:44 UTC, jmulq commented on src/pages/landing/index.tsx
> +        skeleton={8}
Ah right. Maybe rename to `skeletons` or `skeletonAmount` or something?

2022-04-05 13:04 UTC, creativogee commented on src/features/partials/Popups/PlaceBid.tsx
> +      {/* Button section */}
I think it helps to have this type of comment. They're useful as pseudocode also to see things for what they are

2022-04-05 13:10 UTC, creativogee commented on src/features/partials/AssetsListing/index.tsx
> +  loading: boolean
both actually do different things https://redux-toolkit.js.org/rtk-query/usage/queries#frequently-used-query-hook-return-values

2022-04-05 13:13 UTC, creativogee commented on src/features/partials/AssetsListing/index.tsx
> +  data,
It is possible data is not yet fetched by the time this component is rendered, we want to force a re-render once actual data is successfully fetched

2022-04-05 14:43 UTC, merged