feat: dropdown ui for wallet
Vault-Hill/vhc-marketplace-app pull request #81
Opened 2022-04-01 11:54 UTC by chandni-vault-hill

## Description

Created UI for Profile Menu dropdown

2022-04-05 09:48 UTC, jmulq requested changes

2022-04-05 09:48 UTC, jmulq commented on src/features/shared/Footer.tsx
> +    <footer className='bg-white font-avenir' aria-labelledby='footer-heading'>
Don't we have this font as the default for the entire application? So it doesn't need to be explicitly added here? Or am I missing something?

2022-04-05 09:48 UTC, jmulq commented on src/features/shared/header/ConnectWallet.tsx
> +  const subMenuItems: MenuItems[] = [
Should just be logout and the VHC profile balance for this version right?

2022-04-05 09:48 UTC, jmulq commented on src/features/shared/header/ProfileMenu.tsx
> +        <Menu.Item>
Let's grab the VHC balance for the user and display that here instead of hard-coding.

Might require a helper function for this to retrieve the users VHC balance.

2022-04-05 12:49 UTC, jmulq commented
The implementation for getting balance is specific to ether in your latest update right? I think you'll have to do something like this https://github.com/ethers-io/ethers.js/issues/160

Use ethers as we are using ethers. Ping me and I can send over the ABI for the test VHC we are using.

2022-04-05 13:10 UTC, chandni-vault-hill commented on src/features/shared/Footer.tsx
> +    <footer className='bg-white font-avenir' aria-labelledby='footer-heading'>
Moved it to Default.tsx parent div

2022-04-05 16:01 UTC, creativogee approved these changes

2022-04-06 06:30 UTC, chandni-vault-hill commented
> The implementation for getting balance is specific to ether in your latest update right? I think you'll have to do something like this [ethers-io/ethers.js#160](https://github.com/ethers-io/ethers.js/issues/160)
> 
> Use ethers as we are using ethers. Ping me and I can send over the ABI for the test VHC we are using.
> 
> @chandni-vault-hill

Will fix this in another PR

2022-04-06 09:09 UTC, jmulq approved these changes

2022-04-06 09:10 UTC, merged