added web3 wrapper for maintaining persistent connection
Vault-Hill/vhc-marketplace-app pull request #82
Opened 2022-04-04 12:29 UTC by abbeydabiri

Fixes #8 #53 

## Description

Added web3wrapper tag for maintaining persistent connection, this is needed as the current development environment does not maintain persistent connection

2022-04-04 15:26 UTC, anjorinjnr commented
why is this needed? I removed the web3wrapper from the last PR

is there an issue with the current implementation?

2022-04-04 16:17 UTC, abbeydabiri commented
> why is this needed? I removed the web3wrapper from the last PR
> 
> is there an issue with the current implementation?

The issue is that a user needs to sign in anytime the page is refreshed.

2022-04-05 09:44 UTC, jmulq requested changes
So was the app not persisting the web3 connection when refreshing the page? It was on my local instance weirdly?

2022-04-05 11:05 UTC, abbeydabiri commented on src/web3/web3wrapper.ts
> +  if (web3Loaded) {
without the web3wrapper the web3 connection does not persist when the page is refreshed.

2022-04-05 11:20 UTC, abbeydabiri commented on src/web3/web3wrapper.ts
> +  if (web3Loaded) {
yes it can be just return children

2022-04-05 13:43 UTC, anjorinjnr commented
@abbeydabiri  please take a look this PR https://github.com/Vault-Hill/vhc-marketplace-app/pull/85

We don't need this web3 wrapper it doesn't actually wrap anything.  The logic is already extracted inside the ConnectWallet. There was bug in the update I made that's causing the connection to go away. It's fixed in that PR.

2022-04-05 13:55 UTC, closed without merging