Feat/buy now fe integration
Vault-Hill/vhc-marketplace-app pull request #90
Opened 2022-04-06 20:34 UTC by jmulq

## Description

Buy now fill integration into app. This goes alongside a server PR here https://github.com/Vault-Hill/vhc-marketplace-server/pull/28

2022-04-06 22:53 UTC, anjorinjnr requested changes
Please fix the issue with the BuyNow popup, it's importing some object that doesn't exist. And why do we still have fake data.

I made  a commit that should solve the refresh after checkout,

2022-04-07 10:08 UTC, jmulq commented on src/__generated/fetchers/AssetFetcher.ts
>  export const asset$$ =
Amended last commit to resolve this

2022-04-07 10:09 UTC, jmulq commented on src/fake-data/assets.ts
>  export const assets = [
Deleted the fake data we didn't need. Going to let the other guys remove the rest of it as some of the data requires server updates.

2022-04-07 10:11 UTC, jmulq commented
Forgot to commit popup changes, they were hidden in my source control app UI. The refresh issue is still occuring, i.e. the buy now flow completes, but the Asset details UI still shows a buy now button.

2022-04-07 16:37 UTC, anjorinjnr submitted a review, later dismissed

2022-04-07 20:12 UTC, merged