feat: sell asset ui
Vault-Hill/vhc-marketplace-app pull request #98
Opened 2022-04-13 09:12 UTC by chandni-vault-hill

## Description

https://github.com/Vault-Hill/vhc-marketplace-app/issues/39

Figma design

https://www.figma.com/file/I1CfJiJLcSv19IcQyPY7Q0/VaultHill?node-id=5933%3A15634

2022-04-14 11:26 UTC, jmulq requested changes
I think this needs a rethink. Should the components be wired up the to the relevant mutations/queries, or is there going to be a separate PR for that? What the flow here should be doing is getting the relevant data to create an auction or a buy now listing. The server schema shows what's needed to complete these actions. I can run you through it if needs be.

2022-04-14 11:26 UTC, jmulq commented on src/features/partials/Popups/ConfirmSell.tsx
> +import { checkout } from '../../../fake-data/buy-now'
I'm not sure we need fake data for this?

2022-04-14 11:26 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +  const renderSkeleton = () => {
Put this below hooks and handlers

2022-04-14 11:26 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +    const regexPrice = /^[+-]?\d*(?:[.,]\d*)?$/
Whats going on here?

2022-04-14 11:26 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +  const saleTypes: ISaleType[] = [
This might be better like this
```
const saleTypes = {
  buynow: {
    name: ....,
    description: ...
  },
  auction: {
    ...
  }
}
```

2022-04-14 11:26 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +  const currencies: ICurrencyType[] = [{ name: '$VHC' }]
We have currency types in the generated enum file. We need to use these types wherever possible as these are the values that the backend expects when it is sent up something via a mutation.

See the `__generated` folder. This includes all the types on the server.

2022-04-14 11:26 UTC, jmulq commented on src/features/shared/DatePicker.tsx
> +  const CustomInputCalendar = React.forwardRef((property: any, ref: any) => {
What are the types of property and ref? Can they be properly typed?

2022-04-14 11:26 UTC, jmulq commented on src/features/shared/DatePicker.tsx
> +  className = '',
Why does this need to default to an empty string?

2022-04-14 11:26 UTC, jmulq commented on src/features/shared/DatePicker.tsx
> +  const CustomInputCalendar = React.forwardRef((property: any, ref: any) => {
Also what is `property`? Not too sure what it is by the naming or the type.

2022-04-14 11:26 UTC, jmulq commented on src/features/shared/DatePicker.tsx
> +  const onCalendarOpen = () => {
Is there a better way to style it than this?

2022-04-14 11:26 UTC, jmulq commented on src/features/partials/Popups/ConfirmSell.tsx
> +  const [listing] = useAtom(listingAtom)
Where are we setting listing? A listing hasn't been created yet so I'm not sure why we're using the listing atom.

2022-04-14 11:47 UTC, chandni-vault-hill commented on src/features/partials/SellAsset/index.tsx
> +    const regexPrice = /^[+-]?\d*(?:[.,]\d*)?$/
Removed this added validation for amount

2022-04-14 11:48 UTC, chandni-vault-hill commented on src/features/partials/SellAsset/index.tsx
> +  const saleTypes: ISaleType[] = [
Okay

2022-04-14 11:52 UTC, chandni-vault-hill commented on src/features/partials/SellAsset/index.tsx
> +  const currencies: ICurrencyType[] = [{ name: '$VHC' }]
Okay

2022-04-14 11:54 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +  const [listing] = useAtom(listingAtom)
Just created the UI, no wiring with API calls, removed it for now

2022-04-14 12:07 UTC, chandni-vault-hill commented on src/features/shared/DatePicker.tsx
> +  className = '',
Fixed

2022-04-14 12:16 UTC, chandni-vault-hill commented on src/features/partials/SellAsset/index.tsx
> +  const renderSkeleton = () => {
Okay

2022-04-14 12:21 UTC, jmulq commented
Would also be good to see a screenshot of what the flow looks like (not the figma designs)

2022-04-15 04:31 UTC, chandni-vault-hill commented
> Would also be good to see a screenshot of what the flow looks like (not the figma designs)

![image](https://user-images.githubusercontent.com/97173844/163518750-f8bd9ce4-b573-477f-ac60-f4d879b4778b.png)

Screenshot

2022-04-20 10:42 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +import { checkout } from '../../../fake-data/buy-now'
Removed

2022-04-20 10:42 UTC, chandni-vault-hill commented on src/features/shared/DatePicker.tsx
> +  const CustomInputCalendar = React.forwardRef((property: any, ref: any) => {
renamed the variable

2022-04-20 12:31 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +  const [listing] = useAtom(listingAtom)
Wired up with the API

2022-04-20 13:15 UTC, jmulq requested changes

2022-04-20 13:15 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +export interface ISellModal {
Where's this type used?

2022-04-20 13:15 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +export enum SellTypeEnum {
We should be using the same terminology as in the back-end. There are two types of listing, an auction, and a buy now. The sell now terminology is just going to confuse. There is a generated type called `ListingType` that I think you should be using instead.

2022-04-20 13:15 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +                            {...register('amount', {
What does this do? Need to get into the habit of making the code more readable and easier to understand for anyone coming to work on it. Consider splitting logic up into different parts. Seperate render methods and functions in the file that can be called instead of just having everything coded within one block of JSX.

2022-04-20 13:15 UTC, jmulq commented on src/pages/sell-asset/index.tsx
> +      {asset && IsOwner(asset.owner) ? <SellAsset asset={asset} /> : null}
Do we need a check for `asset` here? Do we not check within the child if there is an asset or not?

2022-04-20 13:15 UTC, jmulq commented on src/services/assets.ts
> +    createBuyNow: builder.mutation<boolean, CreateBuyNowInput>({
Why has the result type been changed from `Listing` to `boolean`? The mutation returns a listing right?

2022-04-20 13:15 UTC, jmulq commented on src/services/assets.ts
> +      transformResponse: (response: { data: Asset }) => {
We're converting the response to a bool? Why are we doing this? Am I missing something

2022-04-20 13:15 UTC, jmulq commented on src/services/assets.ts
> +    createAuction: builder.mutation<boolean, AuctionInput>({
This mutation doesn't return a boolean either. Same comments as above. Why is this returning a boolean?

2022-04-20 13:15 UTC, jmulq commented on src/state/atoms/listing.atoms.ts
> +export interface ISellNow {
Ye this is confusing as we're referring to a buy now listing as two things, `BuyNow` and `SellNow`. I'd keep it consistent across the board to avoid confusion.

2022-04-20 13:21 UTC, chandni-vault-hill commented on src/utils/permission.ts
> +export const IsOwner = (assetOwnerAccount: string | undefined): boolean => {
Done

2022-04-20 13:32 UTC, chandni-vault-hill commented on src/utils/permission.ts
> +export const IsOwner = (assetOwnerAccount: string | undefined): boolean => {
Done

2022-04-20 13:37 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +    const currencyAddress = getERC20TokenAddress(sellNow?.currency ?? 'VHC')
Done

2022-04-20 13:45 UTC, chandni-vault-hill commented on src/services/assets.ts
> +    createBuyNow: builder.mutation<boolean, CreateBuyNowInput>({
I am trying to handle if their is any error as not utilizing the response given by the api, just checking if its a success or not

2022-04-20 13:53 UTC, chandni-vault-hill commented on src/pages/sell-asset/index.tsx
> +      {asset && IsOwner(asset.owner) ? <SellAsset asset={asset} /> : null}
Yes, checking in child also

2022-04-20 14:02 UTC, chandni-vault-hill commented on src/state/atoms/listing.atoms.ts
> +export interface ISellNow {
I changed it, just for sell now enum, i would require this as Sell now

2022-04-20 14:03 UTC, chandni-vault-hill commented on src/features/partials/SellAsset/index.tsx
> +export interface ISellModal {
removed

2022-04-20 15:39 UTC, anjorinjnr requested changes
see my comments

2022-04-20 15:39 UTC, anjorinjnr commented on src/utils/permission.ts
> +export class Permission {
there is no need for this to be class.

it should just be a function, and since you're using web3 hook, is should be a hook
```ts
export const useIsOwner = (account:string) => {
     const { account : web3Account } = useWeb3React()
     return web3Account?.toLowerCase() === account.toLowerCase()
}
```

2022-04-20 15:39 UTC, anjorinjnr commented on src/features/partials/SellAsset/index.tsx
> +export interface ISaleType {
don't we already have these types from the generated code?

if not just call it `SaleType` remove the `I`

2022-04-20 15:39 UTC, anjorinjnr commented on src/features/partials/SellAsset/index.tsx
> +export interface ICurrencyType {
see comment above

2022-04-20 15:39 UTC, anjorinjnr commented on src/features/partials/SellAsset/index.tsx
> +        <div className='pt-10 pb-24 lg:pt-0 md:px-3 md:px-6 lg:px-0'>
which one px-3 or px-6?

2022-04-20 15:39 UTC, anjorinjnr commented on src/pages/sell-asset/index.tsx
> +  const params: any = useParams()
`useParams() as { tokenId : string}` or 
`useParams<{tokenId: string}>()`

2022-04-21 08:13 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +        order: '',
Fixed

2022-04-21 10:23 UTC, jmulq commented on src/pages/sell-asset/index.tsx
> +      {asset && IsOwner(asset.owner) ? <SellAsset asset={asset} /> : null}
Theres no need to do the check in both places then right?

2022-04-21 10:51 UTC, chandni-vault-hill commented on src/state/atoms/listing.atoms.ts
> +export interface IBuyNow {
I need this to set values in the sell asset page and then transfer it to the modal, so I created a custom type to get all values which are filled on the page and then using it for swapAssets, and create createBuyNowMutation

2022-04-21 10:51 UTC, chandni-vault-hill commented on src/utils/permission.ts
> +export class Permission {
Done

2022-04-21 11:57 UTC, jmulq requested changes

2022-04-21 11:57 UTC, jmulq commented on src/features/partials/Popups/ConfirmSell.tsx
> +  const handleConfirmNetwork = async () => {
I left a comment about this previously. We aren't confirming a network. We are approving assets for the sale. Could this and other functions/variables be named more appropriately.

2022-04-21 11:57 UTC, jmulq commented on src/features/partials/Popups/ConfirmSell.tsx
> +    const provider = new ethers.providers.Web3Provider(
This line is repeated a lot throughout the codebase. Can we turn it into something reusable so we're not doing this everytime. Maybe a hook? Would that make sense with this @anjorinjnr ?

2022-04-21 11:57 UTC, jmulq commented on src/features/partials/Popups/ConfirmSell.tsx
> +    if (!account || !buyNow) return
Not too sure about this. Could you just have the button that calls this handler disabled if these values aren't there?

2022-04-21 11:57 UTC, jmulq commented on src/features/partials/Popups/ConfirmSell.tsx
> +  const handleSignWallet = async () => {
Name more appropriately. We are creating a buy now order and pushing it up to the db right?

2022-04-21 11:57 UTC, jmulq commented on src/features/partials/SellAsset/index.tsx
> +  const currencies: Currency[] = ['VHC', 'ETH']
There is an enum for currencies in the generated folder. We also don't support ETH so remove this

2022-04-21 11:57 UTC, jmulq commented on src/pages/sell-asset/index.tsx
> +      {isOwner ? <SellAsset asset={asset} /> : null}
`isOwner && <SellAsset />` would work here.

2022-04-21 11:57 UTC, jmulq commented on src/utils/permission.ts
> +import { useWeb3React } from '@web3-react/core'
Probably worth creating and putting this into a hooks folder.

2022-04-21 12:04 UTC, chandni-vault-hill commented on src/features/shared/DatePicker.tsx
> +  const onCalendarOpen = () => {
Tried with the datepicker properties but the datepicker is rendered every time opened, so it removes the class. 
And the font gets applied on 'react-datepicker__month-container' class only.

2022-04-21 12:08 UTC, chandni-vault-hill commented on src/utils/permission.ts
> +import { useWeb3React } from '@web3-react/core'
Okay

2022-04-21 12:09 UTC, chandni-vault-hill commented on src/pages/sell-asset/index.tsx
> +      {isOwner ? <SellAsset asset={asset} /> : null}
Done

2022-04-21 12:26 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +    if (!account || !buyNow) return
Yes I can disable the button but as buyNow or account can be undefined, So i need to keep this check

2022-04-21 13:53 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +    if (!account || !buyNow) return
As the type of account is 

account: string | undefined
And for 
buyNow: <IBuyNow | undefined>

That's the reason, else it gives error

2022-04-21 13:54 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +  const handleConfirmNetwork = async () => {
Need to test this scenario

2022-04-22 04:34 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +    const provider = new ethers.providers.Web3Provider(
Created a hook called "useWeb3Provider" in hooks folder

2022-04-22 04:35 UTC, chandni-vault-hill commented on src/features/partials/Popups/ConfirmSell.tsx
> +    setConfirmedNetwork(approved)
Need to test this scenario, do not have test data

2022-04-25 14:35 UTC, merged